name: local_coin
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  http: ^0.13.4
  flutter_svg: ^1.0.3
  lottie: ^1.3.0
  file_picker: ^5.2.5
  image_picker: ^0.8.6
  shared_preferences: ^2.0.13
  path_provider: ^2.0.9
  country_picker: ^2.0.11
  intl: ^0.17.0
  pin_code_fields: ^7.3.0
  url_launcher: ^6.1.7
  flutter_widget_from_html: ^0.9.1
  font_awesome_flutter: ^8.11.0
  auto_size_text: ^3.0.0
  shimmer: ^2.0.0
  package_info_plus: ^1.4.2
  dotted_border: ^2.0.0+2
  permission_handler: ^10.2.0
  dio: ^4.0.6
  share_plus: 4.0.10+1
  animated_bottom_navigation_bar: 1.1.0
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0

  firebase_core: ^2.4.1
  connectivity_plus: ^3.0.2
  flutter_timer_countdown: ^1.0.3
  awesome_dialog: ^3.0.2
  flutter_app_lock: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  icons_launcher: ^2.1.0

icons_launcher:
  image_path: "assets/icons/applogo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/home_menu_icon/
    - assets/icons/dashboard/
    - assets/icons/notification_icon/
    - assets/icons/menu_icon/
    - assets/icons/
    - assets/animation/
    - assets/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
    - family: Schyler
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700



